export const SAMPLE_VIDEOS = [
  {
    id: '1',
    uri: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    user: {
      id: 'u1',
      username: 'dorji_wangmo',
      displayName: 'Dorji Wangmo',
      avatar: 'https://i.pravatar.cc/150?img=1',
      verified: true,
    },
    description: 'Beautiful sunrise over the Tiger\'s Nest monastery 🏔️ #bhutan #travel #tigersnest',
    song: 'Original Sound - dorji_wangmo',
    likes: 45200,
    comments: 1230,
    shares: 890,
    bookmarks: 2100,
  },
  {
    id: '2',
    uri: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    user: {
      id: 'u2',
      username: 'pema_tshering',
      displayName: 'Pema Tshering',
      avatar: 'https://i.pravatar.cc/150?img=2',
      verified: false,
    },
    description: 'Traditional Bhutanese cooking 🍲 Making ema datshi! #food #bhutan #emadatshi',
    song: 'Bhutanese Folk - Traditional',
    likes: 23100,
    comments: 456,
    shares: 320,
    bookmarks: 890,
  },
  {
    id: '3',
    uri: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    user: {
      id: 'u3',
      username: 'karma_dancer',
      displayName: 'Karma Lhamo',
      avatar: 'https://i.pravatar.cc/150?img=3',
      verified: true,
    },
    description: 'Cham dance practice for Tshechu festival 💃 #dance #bhutan #tshechu #culture',
    song: 'Festival Drums - karma_dancer',
    likes: 67800,
    comments: 2340,
    shares: 1200,
    bookmarks: 4500,
  },
  {
    id: '4',
    uri: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    user: {
      id: 'u4',
      username: 'thinley_adventures',
      displayName: 'Thinley Dorji',
      avatar: 'https://i.pravatar.cc/150?img=4',
      verified: false,
    },
    description: 'Hiking the Snowman Trek, day 15! The views are unreal 🏔️❄️ #hiking #snowmantrek #bhutan',
    song: 'Mountain Vibes - Ambient',
    likes: 89400,
    comments: 3450,
    shares: 5600,
    bookmarks: 12000,
  },
  {
    id: '5',
    uri: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    user: {
      id: 'u5',
      username: 'sonam_arts',
      displayName: 'Sonam Choden',
      avatar: 'https://i.pravatar.cc/150?img=5',
      verified: true,
    },
    description: 'Painting thangka art in my studio 🎨 Hours of meditation in every stroke #art #thangka #bhutan',
    song: 'Lo-fi Meditation - sonam_arts',
    likes: 34500,
    comments: 890,
    shares: 670,
    bookmarks: 3400,
  },
];

export const DISCOVER_CATEGORIES = [
  { id: 'trending', label: '🔥 Trending', color: '#FF2D55' },
  { id: 'dance', label: '💃 Dance', color: '#5856D6' },
  { id: 'food', label: '🍲 Food', color: '#FF9500' },
  { id: 'culture', label: '🏛️ Culture', color: '#34C759' },
  { id: 'travel', label: '✈️ Travel', color: '#007AFF' },
  { id: 'music', label: '🎵 Music', color: '#AF52DE' },
  { id: 'comedy', label: '😂 Comedy', color: '#FFD60A' },
  { id: 'sports', label: '⚽ Sports', color: '#30D158' },
];

export const CURRENT_USER = {
  id: 'me',
  username: 'zhingkham_user',
  displayName: 'Zhingkham User',
  avatar: 'https://i.pravatar.cc/150?img=10',
  bio: 'Welcome to Zhingkham! 🇧🇹',
  followers: 1240,
  following: 356,
  likes: 8900,
  verified: false,
};
